version: '3.9'

services:
  db:
    image: mariadb:11
    container_name: kotlin_mariadb
    environment:
      MARIADB_DATABASE: kotlin_spring_db
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
