spring:
  application:
    name: kotlin-spring-api
  datasource:
    url: jdbc:postgresql://localhost:5438/kotlin-spring-db
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

message: Hello from default profile

---
spring:
  config:
    activate:
      on-profile: prod
message: Hello from prod profile